# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: 'rum')
Ingredient.create(name: 'soda')
Ingredient.create(name: 'lime')
Ingredient.create(name: 'curshed ice')
Ingredient.create(name: 'brown sugar')
Ingredient.create(name: 'fresh mint leaves')
Ingredient.create(name: 'gin')
Ingredient.create(name: 'tonic water')
Ingredient.create(name: 'cucumber')
Ingredient.create(name: 'ice cubes')
Ingredient.create(name: 'orange')
Ingredient.create(name: 'aperol')
Ingredient.create(name: 'prosecco')
Ingredient.create(name: 'cachaca')
Ingredient.create(name: 'ginger beer')
Ingredient.create(name: 'whiskey')
Ingredient.create(name: 'sugar cane syrup')
Ingredient.create(name: 'lime juice')
Ingredient.create(name: 'red wine')
Ingredient.create(name: 'cinnamon sticks')
Ingredient.create(name: 'honey')
Ingredient.create(name: 'orange juice')
Ingredient.create(name: 'vodka')
Ingredient.create(name: 'lemon')
